---
abstract: 'reified escape continuations'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.008001
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.008001
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scope-Escape
provides:
  Scope::Escape:
    file: lib/Scope/Escape.pm
    version: 0.004
  Scope::Escape::Continuation:
    file: lib/Scope/Escape.pm
    version: 0.004
requires:
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
